### ISSUE TITLE
Replace placeholders in table from examples?

### ISSUE THREAD

**Issue by deyanp** [fsprojects/TickSpec#46] opened 2021-05-26 12:19 UTC
Any way to replace automatically placeholders inside a table from the examples?

E.g.

```
Feature: Xxxx

  Scenario Outline: YYY
    Given xxx
    When yyy <Placeholder1>
    | Key | Value |
    | SomeKey | <Placeholder2> |
    Then  zzzz

  Examples:
   | Placeholder1 | Placeholder2 |
   | Value1 | Value2 |
   | Value3 | Value4 |

```

Ideally I would also **not** need to put Placeholder1 in the step definition for the scenario outline to instantiate 2 scenarios ...

I am currently doing it like this as a workaround:

```
module Scenario =
    let scenarios = Dictionary<string,Scenario> ()

    let setCurrent scenario =
        scenarios.[Thread.CurrentThread.ManagedThreadId.ToString()] <- scenario
    let getCurrent () =
        let found, foundScenario = scenarios.TryGetValue(Thread.CurrentThread.ManagedThreadId.ToString())
        if found then Some foundScenario else None
    let getCurrentParameters () =
        getCurrent ()
        |> Option.map (fun foundScenario ->
            foundScenario.Parameters
            |> Map.ofArray )
        |> Option.defaultValue Map.empty

...

    [<Theory; MemberData("scenarios", "Xxxx.feature")>]
    member this.Xxxxx (scenario : Scenario) = 
        Scenario.setCurrent scenario
        scenario.Action.Invoke()

... 
let [<When>] ``yyy (.*)``
    (placeholder1: string)
    (properties: Table)
    (ctx:Context)
    =
   let parameters = Scenario.getCurrentParameters() 
  // here manually replace the values in properties Table ...

```

Any better/more elegant and automated ways?

**Comment by mchaloupka** [comment] 2021-05-27 23:08
Hello,

do I understand the reported defect correctly that the table parameter does not support the placeholders from examples?

**Comment by deyanp** [comment] 2021-05-28 07:36
Hi,

I did not mean this as a defect, simply as sth not supported currently.

Yes, it is about lack of support for placeholders (the value of which is coming from Examples:), which if I am not mistaken is supported in other bdd tools.

I have this cumbersome workaround in place, but maybe there is a better way ...

Br,
Deyan

**Comment by mchaloupka** [comment] 2021-05-28 09:26
Hello,

there is of course a better way! The problem is in this method:
https://github.com/fsprojects/TickSpec/blob/master/TickSpec/FeatureParser.fs#L84

You can see that the code `replace combination s` is used only for the step definitions but not on the bullets/table/doc below.

That feels like a minor change, but it would be good to have it covered by tests. Are you interested in contributing and making a PR for it? If not, I can do it, but I cannot promise how quickly I will get to it.

Regards,
Milos

**Comment by deyanp** [comment] 2021-05-28 12:04
Hmm getting some errors when trying to build ... I am on Ubuntu 20.10 with .NET 5 ... I see some strange things in netfx.props which I have never seen so far ... Maybe you have another hint about this as well?

**Comment by deyanp** [comment] 2021-05-28 12:26
Ignore the above, it seems that If I comment out

`<Import Project="../netfx.props" />`

I can build TickSpec and TickSpec.Tests individually, which should be enough ..

**Comment by deyanp** [comment] 2021-05-28 13:17
@mchaloupka I have created PR #47

**Comment by mchaloupka** [comment] 2021-05-28 23:00
> Ignore the above, it seems that If I comment out
> 
> `<Import Project="../netfx.props" />`
> 
> I can build TickSpec and TickSpec.Tests individually, which should be enough ..

Do you have mono installed? The `netfx.props` was needed to make it building for full .NET Framework on linux. It starts being questionable whether TickSpec should not be migrated to .NET 5 fully. However, before that we should consider whether we can recreate the "emit" functionality.

**Comment by deyanp** [comment] 2021-05-29 16:15
I have no Mono installed (and not at all dying installing it - why would I need it in 2021?).

Not sure what this "emit" functionality is, but yes, migration to .NET 5 is what I suggested on gitter ..

**Comment by mchaloupka** [comment] 2021-05-30 20:51
There is a new release with the merged changes: https://github.com/fsprojects/TickSpec/releases/tag/2.0.1

**Closed by mchaloupka** 2021-05-30 20:51 UTC
